### ISSUE TITLE
Missing texture Error

### ISSUE THREAD

**Issue by mcfilmmakers** [AllTheLayers/ATLCraftCandlesMod#11] opened 2017-09-27 23:36 UTC
Small detail, I know but an error is an error nonetheless. ATL Candles is throwing the following texture error:

`
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: The following texture errors were found.
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: ==================================================
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:   DOMAIN modid
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: --------------------------------------------------
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:   domain modid is missing 1 texture
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:     domain modid is missing a resource manager - it is probably a side-effect of automatic texture processing
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: -------------------------
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:     The missing resources for domain modid are:
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:       textures/blocks/texture_name.png
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: -------------------------
[19:33:34] [main/ERROR] [TEXTURE ERRORS]:     No other errors exist for domain modid
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: ==================================================
[19:33:34] [main/ERROR] [TEXTURE ERRORS]: +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=`

Of note, is that this is the only mod I noticed that doesn't display its name when throwing a texture error. Forge is calling the mod modid instead.

Disabling ATL Candles removes this error.

**Comment by AllTheLayers** [comment] 2017-09-29 07:18
Thanks for the report. I've found the cause and will fix it in the next update.

It's not displaying the right name because of blockstate files with an incorrect texture location.

**Comment by AllTheLayers** [comment] 2017-10-23 23:41
Fixed in MC1.12-Ver1.9.

**Closed as completed by AllTheLayers** 2017-10-23 23:41 UTC
